### ISSUE TITLE
删除zlib

### ISSUE THREAD

**Issue by Berrysoft** [Himself65/OpenArkCompiler#6]
官网代码已经删除了zlib源码，应该是失误放上去的？

**Comment by Himself65** [comment]
没有删除，你别唬我

https://github.com/Himself65/OpenArkCompiler/tree/master/src/third_party/zlib-1.2.11

![image](https://user-images.githubusercontent.com/14026360/64061483-0f4fb080-cc0e-11e9-9c7e-1f101f04281e.png)

**Comment by Berrysoft** [comment]
@Himself65 给你[链接](https://code.opensource.huaweicloud.com/HarmonyOS/OpenArkCompiler/home)，自己去看啊

**Comment by Berrysoft** [comment]
此外这么搞两边不同步真是太麻烦了，有没有办法搞成镜像？

**Comment by Himself65** [comment]
这样得华为开源平台有git hooks才行，不过按照目前的舆论，华为不像是会给外国开源平台传项目

**Comment by Himself65** [comment]
> @Himself65 给你[链接](https://code.opensource.huaweicloud.com/HarmonyOS/OpenArkCompiler/home)，自己去看啊。你放的是自己仓库的链接当然没有删除。

你是不是不看我发的截图

**Comment by Berrysoft** [comment]
> > @Himself65 给你[链接](https://code.opensource.huaweicloud.com/HarmonyOS/OpenArkCompiler/home)，自己去看啊。你放的是自己仓库的链接当然没有删除。
> 
> 你是不是不看我发的截图

哦好吧我看错了，对不起造成了spam
